// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuptuSjvQkXkh_J8QJGfPXIpnah6gqQKE',
    appId: '1:36114951726:web:391562646a87ab6b40f9bf',
    messagingSenderId: '36114951726',
    projectId: 'logitrack-app-cc507',
    authDomain: 'logitrack-app-cc507.firebaseapp.com',
    storageBucket: 'logitrack-app-cc507.firebasestorage.app',
    measurementId: 'G-33F712HHMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG7oKG9_qG0x7dWdHSIgIIr8dq3nTa4ss',
    appId: '1:36114951726:android:da7fde8c63b69e5d40f9bf',
    messagingSenderId: '36114951726',
    projectId: 'logitrack-app-cc507',
    storageBucket: 'logitrack-app-cc507.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3XG70qO-kqzYbKv9yqNwWpuaep-Uvh7Y',
    appId: '1:36114951726:ios:86b5bc6e1bc6a5bb40f9bf',
    messagingSenderId: '36114951726',
    projectId: 'logitrack-app-cc507',
    storageBucket: 'logitrack-app-cc507.firebasestorage.app',
    iosBundleId: 'com.example.logitrackApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3XG70qO-kqzYbKv9yqNwWpuaep-Uvh7Y',
    appId: '1:36114951726:ios:86b5bc6e1bc6a5bb40f9bf',
    messagingSenderId: '36114951726',
    projectId: 'logitrack-app-cc507',
    storageBucket: 'logitrack-app-cc507.firebasestorage.app',
    iosBundleId: 'com.example.logitrackApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuptuSjvQkXkh_J8QJGfPXIpnah6gqQKE',
    appId: '1:36114951726:web:ef55d5ed25c0c18e40f9bf',
    messagingSenderId: '36114951726',
    projectId: 'logitrack-app-cc507',
    authDomain: 'logitrack-app-cc507.firebaseapp.com',
    storageBucket: 'logitrack-app-cc507.firebasestorage.app',
    measurementId: 'G-VCDHCTHLF8',
  );
}
